### ISSUE TITLE
Testing: Numeric Data Types

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#1]
Essentially this module allows users to perform numeric comparisons during an advanced search, and sort browse pages by numeric properties.

To make this possible, administrators need to edit their resource templates and add numeric data types to properties, and then describe their resources using these properties. There are two numeric data types, "timestamp" and "integer."

When editing a resource, a timestamp property should display year/month/day controls and an integer property should display an integer control. The minimum and maximum years for a timestamp property are -292,277,022,656 and 292,277,026,595, respectively. The minimum and maximum numbers for an integer property are -9,007,199,254,740,991 and 9,007,199,254,740,991, respectively. The form should not let you submit an invalid year or integer.

When viewing a resource, a timestamp property should display an accurate date in long form and an integer property should display the integer formatted with commas.

When browsing resources, users should be able to sort by all the numeric data types that are assigned to resource template properties. The sorting must be intuitive, e.g. higher dates/integers should be before lower dates/integers when the sorting order is descending, and inversely on ascending.

When searching resources, users should be able to search by "Date comes before,"  "Date comes after," "Value is less than," and "Value is greater than." The date controls should contain all timestamp properties, and the value controls should contain all integer properties. The search results must be intuitive, e.g. searching on "Date comes after" and "Date comes before" on the same property should result in all resources that have dates that lie between those two dates.

**Comment by mebrett** [comment]
Just to be clear - whole numbers only for the integer input, correct? It's something I'll need to be clear about in the documentation (as measurements for objects are sometimes in cm with decimal points).  Also, how would you recommend indicating units in a way visible to the public (I can think of at least one way, but I'm curious if you have ideas)

**Comment by mebrett** [comment]
Units as in cm, inches, meters, etc.

**Comment by jimsafley** [comment]
I added hour, minute, second to the timestamp data type and advanced search page. They will need thorough testing. On pulling the changes you may notice some "Invalid" errors. If so, you'll need to delete all values from your database of type `numeric:timestamp` due to a change in the valid storage format.

**Comment by mebrett** [comment]
With the previous few updates I didn't have any trouble; on the most recent commit I'm unable to access the items page, instead seeing:

```
Exception
Failed calling Omeka\Api\Representation\ValueRepresentation::jsonSerialize()

Details:

exception 'InvalidArgumentException' with message 'Invalid datetime string, must use ISO 8601' in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/src/DataTyp
```

Error was not resolved until I deleted the items with dates in them. Simply deleting properties from resource templates using Date did not allow items page to load.

**Comment by jimsafley** [comment]
This was due to a change in the valid format to include mandatory zero-padding. The old data did not include zero-padding so it did not validate and threw an error. This shouldn't be a problem from now on.

**Comment by mebrett** [comment]
Visual, not functional, but do we want the extra white space to the right of integer entry?
![screen shot 2018-11-19 at 11 40 22 am](https://user-images.githubusercontent.com/2314070/48721488-072f0300-ebf0-11e8-830d-c66b451e3e4d.png)

**Comment by jimsafley** [comment]
I just committed a change that should remove the whitespace.
