### ISSUE TITLE
Testing: UTC time offset

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#12]
The [timezone-offset branch](https://github.com/omeka-s-modules/NumericDataTypes/tree/timezone-offset) introduces UTC offset capability to the "Timestamp" and "Interval" data types. The form should include an "Offset" select after the "Second" select, and should only be accepted (after submission) unless the "Second" select also has a value. When searching, Omeka should interpret a default offset (i.e. one that is not explicitly set) as UTC (+00:00) and should correctly make the offset adjustments. For example, a search on "Date comes after" for "1900-03-02T05:00:00-04:00" should result in resources with dates that come after "1900-03-02T09:00:00-00:00".

**Comment by mebrett** [comment]
Quick note - offset will not save unless a value is entered for seconds.

**Comment by mebrett** [comment]
I haven't been able to break it, so I'd say it works.

**Comment by jimsafley** [comment]
Resolved in 4379f526129cd929258e049f03d5c6f3a9eda618
