### ISSUE TITLE
Testing: Batch-convert to numeric

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#14]
The [convert-to-numeric branch](https://github.com/omeka-s-modules/NumericDataTypes/tree/convert-to-numeric) introduces a way to batch-convert literal values to numeric values. For example, a user may have hundreds of items with dcterms:date values formatted as ISO 8601 literals. Now, when batch-editing those items, they can select to convert the dcterns:date values to timestamps. Any invalid values will be ignored but logged (so users can find and correct the strings).

Batch editing should work for converting well-formatted literals into all the numeric data types: integer, timestamp, interval, duration. An integer must be a number. A timestamp must be an [ISO 8601 datetime](https://en.wikipedia.org/wiki/ISO_8601#Dates). An interval must be an [ISO 8601 interval](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals). A duration must be an [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by mebrett** [comment]
What is the expected behavior for dates not in ISO format? (March 1786 or something). Skip? Delete?

**Comment by jimsafley** [comment]
Invalid values (i.e. not recognized as ISO) are ignored but logged.

**Comment by mebrett** [comment]
Successfully ran on integer, duration, interval, and timestamp.

**Comment by jimsafley** [comment]
Resolved in feda4b656081e9d9030eed1259300b53fb70f2da
