### ISSUE TITLE
Testing: sanity check for parsing ISO 8601

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#18]
The [iso-8601-hardening branch](https://github.com/omeka-s-modules/NumericDataTypes/tree/iso-8601-hardening) is an attempt to resolve #13, and a sanity check for a more robust way of parsing incoming ISO 8601 strings. The module should behave exactly as before with one small change: users can now set an offset without a second or a minute/second being selected.

**Comment by mebrett** [comment]
Successfully able to save multiple items with an offset but no second information, and no minute/second information.
