### ISSUE TITLE
Error when creating item

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/NumericDataTypes#2]
I created a resource template where Date = timestamp. When I add a new item, I get the error "Warning: DateTime::setTime() expects at most 3 parameters, 4 given in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/src/DataType/Timestamp.php on line 200"

If I try to edit that item, all of the properties (title, creator, etc) are blank, even if they displayed with data when I saved the item.

**Comment by mebrett** [comment]
fwiw my install is on develop and up to date.

**Comment by zerocrates** [comment]
microseconds, the 4th parameter in question, is PHP 7.1+ only. Simply omitting it should be safe and appropriate.
