### ISSUE TITLE
Date search with "equal to"

### ISSUE THREAD

**Issue by hxsllc** [omeka-s-modules/NumericDataTypes#27]
We are finding it very strange that date search must start "the day after" and "the day before".

If the user wants to search for all documents in January, that means they have to enter "Date after 12/30" and "Date before February 1". This is not a good user experience. Is it possible to patch or adjust the code to operate on "less than OR equal to", "greater than OR equal to"? That would be the typical user expectation for date searching, to search within a date range that includes the dates specified.

**Comment by hxsllc** [comment]
Apologies for going off-topic here, perhaps you can direct me to where would be appropriate... but a related issue that I keep noting and forgetting to follow up on is that when you go back to the search form (advanced item search), it's always empty. Even if you use the browser back button. I'm trying to remember the current state of form UX, but in general it seems like most forms don't lose the data so quickly. Would there be a way to enable "sticky" data within Omeka-S settings... or alternatively, some sort of theme / HTML adjustment so that the data fields don't have to be set every time? In particular this is problematic for the fields added by NumericDataTypes module, because via mouse it takes quite a lot of clicks and effort to configure a date search.

**Comment by jimsafley** [comment]
You're at the mercy of your browser. The fields are sticky in Chrome, but not in Firefox. Instead of using your back button, I recommend you click on the "Advanced search" link on the results page. Doing so will guarantee that the form is sticky.

**Comment by hxsllc** [comment]
Checking in on when the update might be released?

**Comment by jimsafley** [comment]
Apologies. We were waiting to merge a branch before making a release, but that has been delayed. I went ahead and made a release without the branch, but including your requested fix. The new version (v1.7.0) should be available tomorrow morning here: https://omeka.org/s/modules/NumericDataTypes/

**Comment by hxsllc** [comment]
I installed 1.7.0, but I'm still not seeing the start and end date being included in search.

This is a search for 1/3/1901 to 1/5/1901. The only document that shows up is 1/4/1901 even though there are several documents dated 1/3/1901.

https://edisondigital.rutgers.edu/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=&numeric%5Bts%5D%5Bgt%5D%5Bpid%5D=20&numeric%5Bts%5D%5Bgt%5D%5Bval%5D=1901-01-03&year=1901&month=1&day=3&hour=&minute=&second=&offset=&numeric%5Bts%5D%5Blt%5D%5Bpid%5D=20&numeric%5Bts%5D%5Blt%5D%5Bval%5D=1901-01-05&year=1901&month=1&day=5&hour=&minute=&second=&offset=&submit=Search#?c=&m=&s=&cv=&xywh=-301%2C-62%2C1441%2C1231

Is there something in the theme that would need to be adjusted? This is the advanced item search page:
https://edisondigital.rutgers.edu/item/search

**Comment by jimsafley** [comment]
You'll need to do something like this in your theme: https://github.com/omeka-s-modules/NumericDataTypes/blob/master/view/common/numeric-data-types-advanced-search.phtml#L10-L56
