### ISSUE TITLE
Test new layout styles for public advanced search inputs

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/NumericDataTypes#28]
[We recently revisited the default input styles for the advanced item search](https://github.com/omeka-s-modules/NumericDataTypes/commit/bc60f0ef6ae86904e0c5f23800d96e0814c7b2dc), and they need to be tested across desktop browsers (Firefox, Chrome, Safari, Edge) and on mobile devices across multiple themes like Default, Center Row, The Daily. These changes are already on the `master` branch.

They should look approximately like the following:

**Desktop**
![image](https://user-images.githubusercontent.com/606764/137529585-c1453051-e16c-464b-8d16-478014296935.png)
 
**Mobile**
![image](https://user-images.githubusercontent.com/606764/137529651-22af4d90-c043-4211-9a08-58afe2e652ec.png)

**Comment by katknow** [comment]
Looks good across themes and browsers (chrome, safari, edge, firefox) on PC & Mac as well as on mobile device.
