### ISSUE TITLE
Date search does not work

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/NumericDataTypes#3]
Finding items with a numeric integer value greater/less than works fine, but I cannot get the find date before/after to work. Search for anything with a value in "Date" before 1800 January 1 seems to just take me back to my browse items page. The url reads `http://dev.omeka.org/mebrett/testomekas/admin/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=&resource_class_id%5B%5D=&resource_template_id%5B%5D=&item_set_id%5B%5D=&site_id=&numeric%5Bts%5D%5Blt%5D%5Bpid%5D=7&numeric%5Bts%5D%5Blt%5D%5Bval%5D=1800-1-1&numeric%5Bts%5D%5Bgt%5D%5Bpid%5D=&numeric%5Bint%5D%5Blt%5D%5Bpid%5D=&numeric%5Bint%5D%5Blt%5D%5Bval%5D=&numeric%5Bint%5D%5Bgt%5D%5Bpid%5D=&numeric%5Bint%5D%5Bgt%5D%5Bval%5D=&submit=Search`

**Comment by jimsafley** [comment]
This should be fixed in 47ffa8d5ec7b52d539980edb7a5729bb7f4978c7

**Comment by mebrett** [comment]
Working now, thank you.
