### ISSUE TITLE
Testing: Timestamp and Interval data types 

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#31]
We've made some significant changes to how we render date/time values. They are now internationalized, which means their format will be localized to the configured locale (found in the Settings page). For example, when the locale is set to "English (United States) [en_US]" the interval `1912-07-28/1918-11-11` should be displayed as "28 July 1914 – 11 November 1918". And when the locale is set to "Română [ro]", it should be displayed as "28 iulie 1914 – 11 noiembrie 1918".

To test this, add "Timestamp" and "Interval" data types to a resource template property. Then test a lot of different configurations of date/times, including dates far into the past and far into the future. Also, test several different locales to see if the month names and "BC" part of the dates are localized.

**Comment by katknow** [comment]
I've tried this with a bunch of different locales as well as dates, but regardless the date stays the same (using the "English (United States) [en_US]" and "Română [ro]" example you provided):
![Screenshot 2022-02-15 at 23-50-20  Untitled  · Items · Katie's Omeka S Testing Site](https://user-images.githubusercontent.com/84726696/154198449-4486ab6d-e7d7-4c99-aa71-9f057636361a.png)
![Screenshot 2022-02-15 at 23-49-44  Fără titlu  · Itemi · Katie's Omeka S Testing Site](https://user-images.githubusercontent.com/84726696/154198453-b8a3c294-55b6-4049-b7de-160c3458731c.png)

I've pulled in both the Numeric Data Types folder and my general install. Do I perhaps need to be on a different branch or something like that? I wondered if I needed to be in the intl-date-formatter branch, but when I switch I get this error:

[](https://omeka.org/s)ParseError
syntax error, unexpected ')'

Details:

ParseError: syntax error, unexpected ')' in /var/www/html/katknow/OmekaSTesting/modules/NumericDataTypes/src/DataType/AbstractDateTimeDataType.php:234
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-loader/src/StandardAutoloader.php(215): Laminas\Loader\StandardAutoloader->loadClass('NumericDataType...', 'namespaces')
#1 [internal function]: Laminas\Loader\StandardAutoloader->autoload('NumericDataType...')
#2 /var/www/html/katknow/OmekaSTesting/modules/NumericDataTypes/src/DataType/Interval.php(13): spl_autoload_call('NumericDataType...')
#3 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-loader/src/StandardAutoloader.php(304): include('/var/www/html/k...')
#4 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-loader/src/StandardAutoloader.php(215): Laminas\Loader\StandardAutoloader->loadClass('NumericDataType...', 'namespaces')
#5 [internal function]: Laminas\Loader\StandardAutoloader->autoload('NumericDataType...')
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/Factory/InvokableFactory.php(31): spl_autoload_call('NumericDataType...')
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(765): Laminas\ServiceManager\Factory\InvokableFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'NumericDataType...', NULL)
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(201): Laminas\ServiceManager\ServiceManager->doCreate('NumericDataType...')
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(153): Laminas\ServiceManager\ServiceManager->get('NumericDataType...')
#10 /var/www/html/katknow/OmekaSTesting/application/src/DataType/Manager.php(24): Laminas\ServiceManager\AbstractPluginManager->get('numeric:interva...')
#11 /var/www/html/katknow/OmekaSTesting/application/src/Api/Representation/ValueRepresentation.php(31): Omeka\DataType\Manager->getForExtract(Object(Omeka\Entity\Value))
#12 /var/www/html/katknow/OmekaSTesting/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(275): Omeka\Api\Representation\ValueRepresentation->__construct(Object(Omeka\Entity\Value), Object(Laminas\ServiceManager\ServiceManager))
#13 /var/www/html/katknow/OmekaSTesting/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(484): Omeka\Api\Representation\AbstractResourceEntityRepresentation->values()
#14 /var/www/html/katknow/OmekaSTesting/application/view/omeka/admin/item/show.phtml(34): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayValues()
#15 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
#16 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#17 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#18 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#19 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#20 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#21 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#22 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#23 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#24 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#25 {main}

**Comment by jimsafley** [comment]
Yes, you're right. I forgot to mention that the feature is on the `intl-date-formatter` branch. Sorry about that. At any rate, I fixed the error so you should be good to go for testing.

**Comment by katknow** [comment]
This works as described across a dates (recent, past, and future) and localizes properly (including "BC" dates).
