### ISSUE TITLE
Testing: Numeric searches without properties

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#33]
The [search-allow-property-exclusion](https://github.com/omeka-s-modules/NumericDataTypes/tree/search-allow-property-exclusion) branch aims to make numeric search results more expected. See #32.

To test this, create a resource template that includes every Numeric data type: Duration, Integer, Interval, Timestamp. Add an item, apply this resource template, and add every type of numeric value. Go to the advanced search page, and for every Numeric search field, search in a way that would result in the item you created, _without_ selecting a property. It works if you get a result. Now search in a way that would _not_ result in the item you created, _without_ selecting a property. It works if you don't get a result. To be thorough, you should probably also search _with_ a property just to confirm that the original behavior still works.

**Comment by katknow** [comment]
This seems to be working for me as well.
