### ISSUE TITLE
how to format date output?

### ISSUE THREAD

**Issue by tdombos** [omeka-s-modules/NumericDataTypes#35]
How can you set the locale for formatting the date output? It is currently day month year, while in Hungarian, for example, we have year month day.

**Comment by jimsafley** [comment]
This is a known bug, but we plan on [adding a fix](https://github.com/omeka-s-modules/NumericDataTypes/compare/get-best-date-pattern) that will require PHP 8.1+.

**Comment by jimsafley** [comment]
The fix is in [the newest version](https://omeka.org/s/modules/NumericDataTypes/). Note that the feature requires PHP 8.1+.
