### ISSUE TITLE
Testing: Duration data type

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#5]
There's a new "duration" data type on the [duration branch](https://github.com/omeka-s-modules/NumericDataTypes/tree/duration). Assign the data type to a property when editing a resource template.

When editing a resource, a duration property should display years/months/days/hours/minutes/seconds controls. When viewing a resource, a duration property should display the inputted duration in a readable form (check for singular/plural).

When browsing resources, users should be able to sort by the duration data types that are assigned to resource template properties. The sorting must be intuitive, e.g. higher durations should be before lower durations when the sorting order is descending, and inversely on ascending.

When searching resources, users should be able to search by "Duration is less than" and "Duration is greater than." The date controls should contain all duration properties. The search results must be intuitive, e.g. searching on "Duration is less than" and "Duration is greater than" on the same property should result in all resources that have dates that lie between those two durations.

**Comment by mebrett** [comment]
Just found an issue - if I conduct a search with Duration, and then go back to advanced search to modify it, nothing loads in the Duration properties and I get the following error in the search form just after "In Site Pool"

`
Notice: Undefined index: interval in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 79 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 80 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 81 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 82 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 83 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 84 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 85 Notice: Undefined index: interval in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 89 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 90 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 91 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 92 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 93 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 94 Notice: Trying to get property of non-object in /websites/omekadev/home/www/mebrett/testomekas/modules/NumericDataTypes/view/common/numeric-data-types-advanced-search.phtml on line 95
`
