### ISSUE TITLE
Testing: Interval data type

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#7]
There's a new "interval" data type on the [interval branch](https://github.com/omeka-s-modules/NumericDataTypes/tree/interval). This should require an module upgrade. Assign the data type to a property when editing a resource template.

When editing a resource, an interval property should display years/months/days/hours/minutes/seconds controls for the start and end of an interval. When viewing a resource, an interval property should display the inputted interval in a readable form.

When searching resources, users should be able to search by "Date in interval." The search results must be intuitive, e.g. searching for "August 2001" should result in items with an interval that includes that datetime.

Important: this addition required major refactoring of the the code, so please make a quick testing pass on the existing numeric data types.

**Comment by mebrett** [comment]
Regarding search - I have an item for the Montgomery bus boycott using the interval data type. 
Start is 1955-12-5 and end is 1956-12-20

However, if I do an advanced search in interval for just 1955 or 1955-12, the item doesn't come up. It only shows up once I add in a day for December which is later than the 5th. I would expect the item to show up on a search for just 1955.

Item property:
![screen shot 2019-01-25 at 10 50 50 am](https://user-images.githubusercontent.com/2314070/51756569-56c9f900-208f-11e9-9352-5f6743bb2224.png)

Search:
![screen shot 2019-01-25 at 10 52 21 am](https://user-images.githubusercontent.com/2314070/51756576-5b8ead00-208f-11e9-8a8e-f2a7d8de8d00.png)

Results do not include item

**Comment by mebrett** [comment]
The Bus Boycott now shows up on searches for 1955, but I'm still having trouble with erratic results if I only search for a year - the [Battle of Baltimore](http://dev.omeka.org/mebrett/testomekas/s/test-site/item/11643) doesn't show in the results for [an advanced search for 1814](http://dev.omeka.org/mebrett/testomekas/s/test-site/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=&resource_class_id%5B%5D=&item_set_id%5B%5D=&numeric%5Bts%5D%5Bgt%5D%5Bpid%5D=&numeric%5Bts%5D%5Blt%5D%5Bpid%5D=&numeric%5Bdur%5D%5Bgt%5D%5Bpid%5D=&numeric%5Bdur%5D%5Blt%5D%5Bpid%5D=&numeric%5Bivl%5D%5Bpid%5D=20&numeric%5Bivl%5D%5Bval%5D=1814&numeric%5Bint%5D%5Bgt%5D%5Bpid%5D=&numeric%5Bint%5D%5Bgt%5D%5Bval%5D=&numeric%5Bint%5D%5Blt%5D%5Bpid%5D=&numeric%5Bint%5D%5Blt%5D%5Bval%5D=&submit=Search)

**Comment by jimsafley** [comment]
Hmm. Now that I think of it more, I didn't write the interval search to accommodate datetimes with reduced accuracy. Rather, it is literally a "Date _in_ interval" search; so searching on the imprecise "1955" does not result in an item with an interval "December 5, 1955 – December 20, 1956", the same as "1814" does not result in an item with an interval "September 12, 1814 – September 15, 1814".

I recognize that this is not necessarily what people will want, so I'll see if I can bring the search more in line with expected behavior.

**Comment by jimsafley** [comment]
I don't see a way forward on this, regrettably.

The module stores date/time intervals as two timestamps (start point and end point) and it converts date/time queries to their equivalent timestamps. So, for example, the module stores the interval "September 12, 1814 – September 15, 1814" as -4900953600, -4900608001. A search on "1814" is essentially a search on -4922899200 (January 1, 1814 00:00:00), which is is outside the interval. Even if the module searched on -4891363201 (December 31, 1814 23:59:59) it would be outside the interval.

I just don't see a way to consistently accommodate an expectation that a search on an imprecise date will result in items that fall outside the interval.

**Comment by zerocrates** [comment]
You don't have an "overlapping interval" type search, do you? i.e., searcher provides an interval and you return items with a date or interval that falls at least partially within the search interval.

I imagine that would be a solution to the problem: you interpret a non-exact date as an interval of its full bounds... but that's maybe a pain, especially if you don't already have the overlapping search. Also full bounds could become annoying for the month level with leap years and so on.

**Comment by jimsafley** [comment]
There's no such search. Given the work involved to implement such a feature, and that it's a larger scope than this branch was intended, I think it's best to release the module as-is and document the limitation:

> When using "Date in interval" we recommend entering a date/time that's as precise as possible. Entering a non-exact date/time may have unexpected results, as it may fall outside an item's interval.
