### ISSUE TITLE
Testing: Form element refactoring

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#9]
The [refactor-forms branch](https://github.com/omeka-s-modules/NumericDataTypes/tree/refactor-forms) introduces some considerable refactoring to the timestamp, interval, and duration form elements. This is necessary to make the elements reusable by other modules.

The UI and behavior should be _exactly_ the same, in both the resource form and the advanced search page. Test everything out as before. You should notice no changes.

**Comment by mebrett** [comment]
Everything seems to be working exactly as before.
